amcl:
  ros__parameters:
    use_sim_time: False  # 是否使用仿真时间（False表示使用真实时间）
    alpha1: 0.1  # 里程计模型噪声参数（旋转分量1）
    alpha2: 0.1  # 里程计模型噪声参数（旋转分量2）
    alpha3: 0.1  # 里程计模型噪声参数（平移分量1）
    alpha4: 0.1  # 里程计模型噪声参数（平移分量2）
    alpha5: 0.1  # 全向机器人额外噪声参数
    base_frame_id: "base_footprint"  # 机器人基坐标系ID
    beam_skip_distance: 0.5  # 激光束跳跃检测的距离阈值
    beam_skip_error_threshold: 0.9  # 激光束跳跃的误差阈值
    beam_skip_threshold: 0.3  # 激光束跳跃的概率阈值
    do_beamskip: false  # 是否启用激光束跳跃检测（减少计算量）
    global_frame_id: "map"  # 全局地图坐标系ID
    lambda_short: 0.1  # 短距离激光模型的衰减参数
    laser_likelihood_max_dist: 2.0  # 激光似然计算的最大距离
    laser_max_range: 20.0  # 激光传感器最大有效距离
    laser_min_range: 0.4  # 激光传感器最小有效距离
    laser_model_type: "likelihood_field"  # 激光匹配模型（似然场模型）
    max_beams: 60  # 每次更新使用的激光束数量
    max_particles: 2000  # 粒子滤波器最大粒子数
    min_particles: 500  # 粒子滤波器最小粒子数
    odom_frame_id: "odom"  # 里程计坐标系ID
    pf_err: 0.05  # 粒子滤波重采样的误差阈值
    pf_z: 0.99  # 粒子滤波重采样的置信度阈值
    recovery_alpha_fast: 0.0  # 快速恢复的粒子分散系数（0表示禁用）
    recovery_alpha_slow: 0.0  # 慢速恢复的粒子分散系数（0表示禁用）
    resample_interval: 1  # 重采样间隔（每n次更新重采样一次）
    robot_model_type: nav2_amcl::OmniMotionModel  # 机器人运动模型（全向模型）
    save_pose_rate: 1.0  # 保存位姿的频率（Hz）
    sigma_hit: 0.2  # 似然场模型中命中的标准差
    tf_broadcast: true  # 是否广播map到base_link的TF变换
    transform_tolerance: 1.0  # TF变换的容忍时间（秒）
    update_min_a: 0.2  # 触发定位更新的最小旋转角度（弧度）
    update_min_d: 0.25  # 触发定位更新的最小平移距离（米）
    z_hit: 0.5  # 似然场模型中"命中"的权重
    z_max: 0.05  # 似然场模型中"超出范围"的权重
    z_rand: 0.5  # 似然场模型中"随机"的权重
    z_short: 0.05  # 似然场模型中"短距离"的权重
    scan_topic: /scan  # 激光扫描数据的订阅话题

amcl_map_client:
  ros__parameters:
    use_sim_time: False  # AMCL地图客户端是否使用仿真时间

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False  # AMCL节点是否使用仿真时间

bt_navigator:
  ros__parameters:
    use_sim_time: False  # 是否使用仿真时间
    global_frame: map  # 全局坐标系ID
    robot_base_frame: base_link  # 机器人基坐标系ID
    odom_topic: /odom  # 里程计话题
    bt_loop_duration: 10  # 行为树循环周期（毫秒）
    default_server_timeout: 20  # 服务默认超时时间（秒）
    wait_for_service_timeout: 1000  # 等待服务的超时时间（毫秒）
    # 以下为行为树节点插件列表，包含路径计算、路径跟随、恢复行为等
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node  # 计算到目标点路径的行为树节点
      - nav2_compute_path_through_poses_action_bt_node  # 计算经过多个点的路径的节点
      - nav2_smooth_path_action_bt_node  # 平滑路径的节点
      - nav2_follow_path_action_bt_node  # 跟随路径的节点
      - nav2_spin_action_bt_node  # 旋转动作节点
      - nav2_wait_action_bt_node  # 等待动作节点
      - nav2_assisted_teleop_action_bt_node  # 辅助遥控节点
      - nav2_back_up_action_bt_node  # 后退动作节点
      - nav2_drive_on_heading_bt_node  # 沿指定方向行驶节点
      - nav2_clear_costmap_service_bt_node  # 清除代价地图服务节点
      - nav2_is_stuck_condition_bt_node  # 判断是否卡住的条件节点
      - nav2_goal_reached_condition_bt_node  # 判断是否到达目标的条件节点
      - nav2_goal_updated_condition_bt_node  # 判断目标是否更新的条件节点
      - nav2_globally_updated_goal_condition_bt_node  # 判断全局目标是否更新的节点
      - nav2_is_path_valid_condition_bt_node  # 判断路径是否有效的条件节点
      - nav2_initial_pose_received_condition_bt_node  # 判断是否收到初始位姿的节点
      - nav2_reinitialize_global_localization_service_bt_node  # 重新初始化全局定位的节点
      - nav2_rate_controller_bt_node  # 速率控制节点
      - nav2_distance_controller_bt_node  # 距离控制节点
      - nav2_speed_controller_bt_node  # 速度控制节点
      - nav2_truncate_path_action_bt_node  # 截断路径的节点
      - nav2_truncate_path_local_action_bt_node  # 截断局部路径的节点
      - nav2_goal_updater_node_bt_node  # 更新目标的节点
      - nav2_recovery_node_bt_node  # 恢复行为节点
      - nav2_pipeline_sequence_bt_node  # 流水线序列节点
      - nav2_round_robin_node_bt_node  # 轮询节点
      - nav2_transform_available_condition_bt_node  # 判断TF变换是否可用的节点
      - nav2_time_expired_condition_bt_node  # 判断时间是否过期的节点
      - nav2_path_expiring_timer_condition  # 路径过期计时器条件节点
      - nav2_distance_traveled_condition_bt_node  # 判断移动距离的条件节点
      - nav2_single_trigger_bt_node  # 单次触发节点
      - nav2_goal_updated_controller_bt_node  # 目标更新控制器节点
      - nav2_is_battery_low_condition_bt_node  # 判断电池是否低电量的节点
      - nav2_navigate_through_poses_action_bt_node  # 导航经过多个点的节点
      - nav2_navigate_to_pose_action_bt_node  # 导航到目标点的节点
      - nav2_remove_passed_goals_action_bt_node  # 移除已通过目标的节点
      - nav2_planner_selector_bt_node  # 规划器选择节点
      - nav2_controller_selector_bt_node  # 控制器选择节点
      - nav2_goal_checker_selector_bt_node  # 目标检查器选择节点
      - nav2_controller_cancel_bt_node  # 取消控制器的节点
      - nav2_path_longer_on_approach_bt_node  # 接近目标时路径变长的节点
      - nav2_wait_cancel_bt_node  # 取消等待的节点
      - nav2_spin_cancel_bt_node  # 取消旋转的节点
      - nav2_back_up_cancel_bt_node  # 取消后退的节点
      - nav2_assisted_teleop_cancel_bt_node  # 取消辅助遥控的节点
      - nav2_drive_on_heading_cancel_bt_node  # 取消沿方向行驶的节点
      - nav2_is_battery_charging_condition_bt_node  # 判断是否在充电的节点

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False  # BT导航器节点是否使用仿真时间

controller_server:
  ros__parameters:
    use_sim_time: False  # 是否使用仿真时间
    controller_frequency: 20.0  # 控制器更新频率（Hz）
    min_x_velocity_threshold: 0.001  # x方向最小速度阈值（低于此值视为停止）
    min_y_velocity_threshold: 0.001  # y方向最小速度阈值
    min_theta_velocity_threshold: 0.001  # 旋转最小速度阈值
    progress_checker_plugin: "progress_checker"  # 进度检查器插件名称
    goal_checker_plugin: "goal_checker"  # 目标检查器插件名称
    controller_plugins: ["FollowPath"]  # 控制器插件列表

    # 进度检查器参数
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"  # 简单进度检查器插件
      required_movement_radius: 0.3  # 要求的最小移动半径（米，用于判断是否卡滞）
      movement_time_allowance: 30.0  # 允许的最大移动时间（秒，超时则触发恢复）
    # 目标检查器参数
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"  # 简单目标检查器插件
      xy_goal_tolerance: 0.5  # xy方向到达目标的容忍误差（米）
      yaw_goal_tolerance: 0.5  # 航向角到达目标的容忍误差（弧度）
      stateful: True  # 是否启用状态化检查（接近目标后严格检查）
    # DWB局部规划器参数（作为控制器插件）
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"  # DWB局部规划器插件
      debug_trajectory_details: True  # 是否输出轨迹调试信息
      min_vel_x: 0.0  # x方向最小速度（米/秒）
      min_vel_y: 0.0  # y方向最小速度（米/秒）
      max_vel_x: 0.3  # x方向最大速度（米/秒）
      max_vel_y: 0.3  # y方向最大速度（米/秒）
      max_vel_theta: 0.5  # 最大旋转速度（弧度/秒）
      min_speed_xy: 0.0  # xy方向最小合速度（米/秒）
      max_speed_xy: 0.5  # xy方向最大合速度（米/秒）
      min_speed_theta: 0.0  # 最小旋转速度（弧度/秒）
      acc_lim_x: 0.5  # x方向加速度限制（米/秒²）
      acc_lim_y: 0.5  # y方向加速度限制（米/秒²）
      acc_lim_theta: 0.3  # 旋转加速度限制（弧度/秒²）
      decel_lim_x: -0.5  # x方向减速度限制（米/秒²）
      decel_lim_y: -0.5  # y方向减速度限制（米/秒²）
      decel_lim_theta: -0.5  # 旋转减速度限制（弧度/秒²）
      vx_samples: 30  # x方向速度采样数
      vy_samples: 30  # y方向速度采样数
      vtheta_samples: 30  # 旋转速度采样数
      sim_time: 1.7  # 轨迹仿真时间（秒）
      linear_granularity: 0.05  # 线性方向轨迹 granularity（米）
      angular_granularity: 0.025  # 角方向轨迹 granularity（弧度）
      transform_tolerance: 0.2  # TF变换容忍时间（秒）
      xy_goal_tolerance: 0.25  # xy方向目标容忍度（米）
      trans_stopped_velocity: 0.08  # 平移停止的速度阈值（米/秒）
      short_circuit_trajectory_evaluation: True  # 是否提前终止差轨迹的评价
      stateful: True  # 是否启用状态化控制（接近目标时调整行为）
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]  # 评价器列表
      BaseObstacle.scale: 70.0  # 基础障碍物评价器的权重
      PathAlign.scale: 45.0  # 路径对齐评价器的权重
      PathAlign.forward_point_distance: 0.1  # 路径对齐的前向点距离（米）
      GoalAlign.scale: 30.0  # 目标对齐评价器的权重
      GoalAlign.forward_point_distance: 0.1  # 目标对齐的前向点距离（米）
      PathDist.scale: 32.0  # 路径距离评价器的权重
      GoalDist.scale: 24.0  # 目标距离评价器的权重
      RotateToGoal.scale: 15.0  # 转向目标评价器的权重
      RotateToGoal.slowing_factor: 3.0  # 转向目标时的减速因子
      RotateToGoal.lookahead_time: 0.5  # 转向目标的前瞻时间（秒）

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False  # 控制器节点是否使用仿真时间

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 8.0  # 代价地图更新频率（Hz）
      publish_frequency: 8.0  # 代价地图发布频率（Hz）
      global_frame: odom  # 局部代价地图的全局坐标系（里程计系）
      robot_base_frame: base_link  # 机器人基坐标系
      use_sim_time: False  # 是否使用仿真时间
      rolling_window: true  # 是否使用滚动窗口（随机器人移动更新）
      width: 10  # 代价地图宽度（米）
      height: 10  # 代价地图高度（米）
      resolution: 0.1  # 代价地图分辨率（米/单元格）
      robot_radius: 0.2  # 机器人半径（米，用于碰撞检测）
      plugins: ["voxel_layer", "inflation_layer"]  # 代价地图插件列表
      inflation_layer:  # 膨胀层（将障碍物向外膨胀，避免碰撞）
        plugin: "nav2_costmap_2d::InflationLayer"  # 膨胀层插件
        cost_scaling_factor: 2.0  # 代价缩放因子（值越大，膨胀代价衰减越快）
        inflation_radius: 0.65  # 膨胀半径（米）
      voxel_layer:  # 体素层（处理三维障碍物）
        plugin: "nav2_costmap_2d::VoxelLayer"  # 体素层插件
        enabled: True  # 是否启用
        publish_voxel_map: True  # 是否发布体素地图
        origin_z: 0.0  # 体素地图Z轴原点
        z_resolution: 0.05  # Z轴分辨率（米）
        z_voxels: 16  # Z轴体素数量
        max_obstacle_height: 2.0  # 最大障碍物高度（米）
        mark_threshold: 0  # 标记障碍物的阈值
        observation_source: livox  # 观测源名称（激光雷达）
        livox:  # 激光雷达观测参数
           topic: /scan  # 激光数据话题
           sensor_frame: livox_frame  # 激光雷达坐标系
           max_obstacle_height: 2.0  # 激光雷达检测的最大障碍物高度
           clearing: True  # 是否用于清除障碍物（移动后移除旧障碍）
           marking: True  # 是否用于标记障碍物
           data_type: "LaserScan"  # 数据类型（激光扫描）
      static_layer:  # 静态层（地图静态障碍）
        map_subscribe_transient_local: True  # 是否订阅瞬态本地地图
      always_send_full_costmap: True  # 是否总是发送完整代价地图
  local_costmap_client:
    ros__parameters:
      use_sim_time: False  # 局部代价地图客户端是否使用仿真时间
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False  # 局部代价地图节点是否使用仿真时间


global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 8.0  # 更新频率（Hz）
      publish_frequency: 8.0  # 发布频率（Hz）
      global_frame: map  # 全局坐标系（地图系）
      robot_base_frame: base_link  # 机器人基坐标系
      use_sim_time: False  # 是否使用仿真时间
      robot_radius: 0.2  # 机器人半径（米）
      resolution: 0.1  # 分辨率（米/单元格）
      track_unknown_space: true  # 是否追踪未知区域
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]  # 插件列表
      obstacle_layer:  # 障碍物层（动态障碍）
        plugin: "nav2_costmap_2d::ObstacleLayer"  # 障碍物层插件
        enabled: True  # 是否启用
        observation_sources: scan  # 观测源（激光雷达）
        scan:  # 激光雷达参数
          topic: /scan  # 激光数据话题
          sensor_frame: livox_frame  # 激光雷达坐标系
          max_obstacle_height: 2.0  # 最大障碍物高度
          clearing: True  # 是否用于清除障碍物
          marking: True  # 是否用于标记障碍物
          data_type: "LaserScan"  # 数据类型
      static_layer:  # 静态层（地图静态障碍）
        plugin: "nav2_costmap_2d::StaticLayer"  # 静态层插件
        map_subscribe_transient_local: True  # 是否订阅瞬态本地地图
      inflation_layer:  # 膨胀层
        plugin: "nav2_costmap_2d::InflationLayer"  # 膨胀层插件
        cost_scaling_factor: 2.0  # 代价缩放因子
        inflation_radius: 0.65  # 膨胀半径（米）
      always_send_full_costmap: True  # 是否总是发送完整代价地图
  global_costmap_client:
    ros__parameters:
      use_sim_time: False  # 全局代价地图客户端是否使用仿真时间
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False  # 全局代价地图节点是否使用仿真时间


map_server:
  ros__parameters:
    use_sim_time: False  # 是否使用仿真时间
    yaml_filename: "9-room-2.yaml"  # 地图配置文件路径

map_saver:
  ros__parameters:
    use_sim_time: False  # 是否使用仿真时间
    save_map_timeout: 5000.0  # 保存地图的超时时间（毫秒）
    free_thresh_default: 0.25  # 默认为自由空间的阈值（占空比）
    occupied_thresh_default: 0.65  # 默认为障碍物的阈值（占空比）
    map_subscribe_transient_local: False  # 是否订阅瞬态本地地图


planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0  # 预期规划器频率（Hz）
    use_sim_time: False  # 是否使用仿真时间
    planner_plugins: ["GridBased"]  # 规划器插件列表
    GridBased:  # 基于网格的规划器
      plugin: "nav2_smac_planner/SmacPlanner2D"  # SMAC规划器插件（2D）
      tolerance: 0.2  # 到达目标的容忍误差（米）
      use_astar: true  # 是否使用A*算法（false则使用Dijkstra）
      allow_unknown: true  # 是否允许路径经过未知区域
    

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False  # 规划器节点是否使用仿真时间


recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw  # 代价地图话题
    footprint_topic: local_costmap/published_footprint  # 机器人足迹话题
    cycle_frequency: 10.0  # 恢复行为循环频率（Hz）
    recovery_plugins: ["spin", "back_up", "wait"]  # 恢复插件列表
    spin:  # 旋转恢复
      plugin: "nav2_recoveries/Spin"  # 旋转恢复插件
    back_up:  # 后退恢复
      plugin: "nav2_recoveries/BackUp"  # 后退恢复插件
    wait:  # 等待恢复
      plugin: "nav2_recoveries/Wait"  # 等待恢复插件
    global_frame: odom  # 全局坐标系
    robot_base_frame: base_link  # 机器人基坐标系
    transform_timeout: 0.1  # TF变换超时时间（秒）
    use_sim_time: False  # 是否使用仿真时间
    simulate_ahead_time: 2.0  # 前瞻仿真时间（秒）
    max_rotational_vel: 1.0  # 最大旋转速度（弧度/秒）
    min_rotational_vel: 0.4  # 最小旋转速度（弧度/秒）
    rotational_acc_lim: 3.2  # 旋转加速度限制（弧度/秒²）


robot_state_publisher:
  ros__parameters:
    use_sim_time: False  # 机器人状态发布器是否使用仿真时间